---
title: "Intro to R Homework"
output: html_notebook
---

1. 
```{r}
sex <- c("M", "F", "M", "F", "M", "F", "M", "F", "M", "F", "M", "F")
stage <- c(1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2)
treatment <- c(rep("A", 4), rep("B", 4), rep("P", 4))
myc <- c(2343, 457, 4593, 9035, 3450, 3524, 958, 1053, 8674, 3424, 463, 5105)
meta <- data.frame(sex, stage, treatment, myc)
sampleID <- c("sample1", "sample2", "sample3", "sample4", "sample5", "sample6", "sample7", "sample8", "sample9", "sample10", "sample11", "sample12")
rownames(meta) <- sampleID
meta
```

2. 
```{r}
meta[c(1, 3)]
```
```{r}
meta[c(5, 7, 9, 10),]
```
```{r}
filter(meta, meta$treatment == "P")
```
```{r}
select(filter(meta, meta$myc > 5000), stage, treatment)
```
```{r}
meta[c(1:2, 4)]
```
```{r}
meta[c(1:6, 10:12),]
```
```{r}
meta[1:6,]
```
```{r}
pre_treatment <- c("T", rep("F", 3), rep("T", 2), "F", "T", "F", "F", "T", "T")
meta <- cbind(pre_treatment, meta)
```
```{r}
colnames(meta) <- c("pre_treatment", "A", "B", "C", "D")
meta
```

